# Sets the build number to a format that can be used to generate the package
# version numbers for NuGet, when using the `byBuildNumber` versioning scheme.
name: "$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)"

# This job is setup to only build on commits to `master`
# _when files in the projects we're going to pack_ are changed. This is intended
# to reduce churn in projects which depend on these packages since every build
# will push a new version of each of these packages.
trigger:
  batch: true
  branches:
    include:
    - 'master'
  paths:
    include:
      - "src/"
      - "Directory.Build.*"
      - "FGS.Foundation.*"
      - "azure-pipelines/Master/"

pr: none

stages:

- template: ./BuildAndPushPackage.yml
