# Publish NuGet packages from PUMP that can be shared with other projects.

# Sets the build number to a format that can be used to generate the package
# version numbers for NuGet, when using the `byBuildNumber` versioning scheme.
name: "$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)"

# This job is setup to only build on commits to foxguardsolutions/pump/master
# when files in the projects we're going to pack are changed. This is intended
# to reduce churn in projects which depend on these packages since every build
# will push a new version of each of these packages.
trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
      - "Extensions/FGS.[!Pump]*/*"
pr: none

pool:
  vmImage: "windows-latest"

steps:
  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: pack
      packagesToPack: "Extensions/FGS.[!Pump]*/*.csproj"
      versioningScheme: byBuildNumber
      arguments: --configuration Release

  - task: DotNetCoreCLI@2
    displayName: "dotnet push"
    inputs:
      command: push
      nuGetFeedType: internal
      publishVstsFeed: InternalDevelopment
